### ISSUE TITLE
main.cu   __global__ void updateEmptyNodeInfo(int *BaseAddressArray_d,OctNode *NodeArray,int size);

### ISSUE THREAD

**Issue by RKGalaxy-Luo** [DavidXu-JJ/PoissonRecon_GPU#3]
In this function, this place needs extra attention at level maxDepth, there will be no child nodes at level maxDepth, the parameter "basePos" is obviously a random number. Although it will not affect the algorithm, but this is obviously more rigorous writing.
![1](https://github.com/DavidXu-JJ/PoissonRecon_GPU/assets/104077812/8e02532b-0b64-4789-b13d-8ffd30c573bb)

**Comment by DavidXu-JJ** [comment]
https://github.com/DavidXu-JJ/PoissonRecon_GPU/blob/618acfde52280dd9a7b4bbc44e7a69289c8cf6a5/main.cu#L450-L454
It seems that depth won't get to maxDepth?

I realize from your comments that there are lots of optimization about memory allocation can be made about the children info of leaf node. They don't need to be allocated if wish to save the memory.

**Comment by RKGalaxy-Luo** [comment]
thanks a lot, now I have run this project successfully. I rebuild some classical model like ‘rabbit’, it works well, however, when try to rebuild some point clouds model like 'human body', it will be divergent at laplace solver.  I really want to figure out why divergent and I've contacted you at email.
I will really appreciate it if I can get your help!
![6cf9ac94290d4d47609b5fee370b9932](https://github.com/DavidXu-JJ/PoissonRecon_GPU/assets/104077812/e2a13fd4-f4c7-4b27-8d6f-e143447cb6bb)

**Comment by DavidXu-JJ** [comment]
Hi,
For your email, I notice it today. But as is mentioned in my profile, I will only reply to the email that informs me who they are.

Back to the technical problem.
First I'm happy to see you organize the algorithm implementation into a good structure.
This repo was written when I was still not yet familiar with project organizing severals years ago. And also I was writing the code in a very nervous circumstance. (I remember I need to finish it in three weeks) By the way, this project initially was not written to open the source.
As a result, almost all core part was written in a single main file. And the code itself was not organized after I finished it (This is apparently not good)
I know it's hard to make a clean and neat codebase.
Congrats for your current achievement!

Then for your question,
Since the number of the first degree octree nodes may not be so much large. You can first try to print the divergence of these region.
Suppose you already get the right parameter of the sparse matrix. (So maybe you can first double-check the matrix for the first degree octree) Then it comes to an optimization problem for solution x with CG solver. Since this is not a big linear system, you can check whether this is a valid linear system manually or in a cpu implementation solver.

I'm not so much clear about the smallest details about the problem you met in your special case. You can try to check the rough solution I mention above.

**Comment by DavidXu-JJ** [comment]
Warm Remind:
I don't upload the file I use to this repo because potentially I may don't have the right to distribute the data.
Maybe you should keep an eye on this problem for your repo.

**Comment by RKGalaxy-Luo** [comment]
您好，我目前是武汉理工大学的一位在读研究生，研究的方向其实涉及到三维重建，但一些理论知识可能有些欠缺，我其实前段时间针对您之前的项目做了一个优化（如果您有兴趣可以参考：RKGalaxy-Luo/Poisson-Surface-Reconstruction-GPU: Reconstruct surface using point clouds and it's a GPU-accelerated implementation (github.com)，同时也非常欢迎您也加入该项目）。目前项目主体还是您之前的思想，主要是数值计算方面我并不是很了解，如果方便的话，可能需要您的不吝赐教。再次感谢您的积极回复




破箱子里的旧信
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DavidXu-JJ/PoissonRecon_GPU"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月9日(星期二) 晚上10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DavidXu-JJ/PoissonRecon_GPU] main.cu   __global__ void updateEmptyNodeInfo(int *BaseAddressArray_d,OctNode *NodeArray,int size); (Issue #3)





 
Hi,
 For your email, I notice it today. But as is mentioned in my profile, I will only reply to the email that informs me who they are.
 
Back to the technical problem.
 First I'm happy to see you organize the algorithm implementation into a good structure.
 This repo was written when I was still not yet familiar with project organizing severals years ago. And also I was writing the code in a very nervous circumstance.
 As a result, almost all core part was written in a single main file. And the code itself was not organized after I finished it (This is apparently not good)
 I know it's hard to make a clean and neat codebase.
 Congrats for your current achievement!
 
Then for your question,
 Since the number of the first degree octree nodes may not be so much large. You can first try to print the divergence of these region.
 Suppose you already get the right parameter of the sparse matrix. (So maybe you can first double-check the matrix for the first degree octree) Then it comes to an optimization problem for solution x with CG solver. Since this is not a big linear system, you can check whether this is a valid linear system manually or in a cpu implementation solver.
 
I'm not so much clear about the smallest details about the problem you met in your special case. You can try to check the rough solution I mention above.

**Comment by RKGalaxy-Luo** [comment]
请问您主页中涉及的邮箱（xujw2023@shanghaitech.edu.cn）是否还在使用，我可以通过邮箱与您取得实质联系，非常感谢

**Comment by DavidXu-JJ** [comment]
This mail is still active. But I already issue a friend application in QQ. Maybe we can talk in private thread.

**Comment by RKGalaxy-Luo** [comment]
我目前没有收到好友申请，请确认一下好友申请的账号是否是：954910694

**Comment by DavidXu-JJ** [comment]
I send my QQ to your email. You can add it if you still don't receive my application.
